server:
  port: 8080
  servlet:
    context-path: /auth
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cs544_auth
    username: root
    password: root
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
#logging:
#  level:
#    root: DEBUG