server:
  port: 8080
  servlet:
    context-path: /auth
spring:
  datasource:
    url: jdbc:mysql://mysqldb/cs544_auth
    username: root
    password: root
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: health
app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ
#logging:
#  level:
#    root: DEBUG