version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE= cs544_auth
      - MYSQL_ROOT_PASSWORD= root
      - MYSQL_ROOT_HOST= '%'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - cs544
  auth-service:
    depends_on:
      - mysqldb
    container_name: auth-service
    build:
      context: auth-service
      dockerfile: Dockerfile
    #    restart: on-failure
    image: cs544/auth-service:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/cs544_auth?useSSL=false",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "create-drop"
          }'
    stdin_open: true
    tty: true
    networks:
      - cs544
networks:
  cs544:
    driver: bridge
volumes:
  db:
    driver: bridge