server:
  port: 8083
  servlet:
    context-path: /member
spring:
  data:
    mongodb:
      uri: mongodb://root:root@mongodb-member/cs544_member

services:
  auth:
    host: auth-service
    port: 8080
    context-path: /auth/
  streaming:
    host: sport-service
    port: 8081
    context-path: /sport/
#logging:
#  level:
#    root: DEBUG