server:
  port: 8083
  servlet:
    context-path: /member
management:
  endpoints:
    web:
      exposure:
        include: health
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gameDb
services:
  auth:
    host: localhost
    port: 8080
    context-path: /auth/
  streaming:
    host: localhost
    port: 8081
    context-path: /sport/
#spring:
#  data:
#    mongodb:
#      username: root
#      password: root
#      host: localhost
#      port: 27017
#logging:
#  level:
#    root: DEBUG