server:
  port: 8082
  servlet:
    context-path: /stream
management:
  endpoints:
    web:
      exposure:
        include: health
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api.html
#logging:
#  level:
#    root: DEBUG