server:
  port: 8082
  servlet:
    context-path: /stream

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs544?useSSL=false
    username: root
    password: root
      
#  mvc:
#    view:
#      prefix: /WEB-INF/views
#      suffix: .jsp
#logging:
#  level:
#    root: DEBUG