server:
  port: 8081
  servlet:
    context-path: /sport

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs544?useSSL=false
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://localhost:27017/gameDb
      
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
#logging:
#  level:
#    root: DEBUG