server:
  port: 8081
  servlet:
    context-path: /sport
management:
  endpoints:
    web:
      exposure:
        include: health
spring:
  data:
    mongodb:
      uri: mongodb://root:root@mongodb/cs544
services:
  auth:
    host: auth-service
    port: 8080
    context-path: /auth/
  streaming:
    host: streaming-service
    port: 8082
    context-path: /stream/
#logging:
#  level:
#    root: DEBUG