version: "3.9" #version of docker-compose
services:
  web:
    image: tomcat:latest
    container_name: tomcat-container
    ports:
      - "8080:8080"
    links:
      - db:mysql-container
  db:
    image: mysql/mysql-server:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cs544