apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-sport-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi