server:
  port: 8082
  servlet:
    context-path: /stream
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gameDb
      
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
#logging:
#  level:
#    root: DEBUG